[versions]
componentsResources = "1.10.0"
foundation = "1.10.0"
kotlin = "2.3.0"
compose = "1.10.0"
agp = "9.0.0"
androidx-activityCompose = "1.12.2"
kotlinxCoroutinesCore = "1.10.2"
material3 = "1.10.0-alpha05"
maven-publish = "0.35.0"
firebaseCommonKtx = "21.0.0"
firebaseBom = "34.8.0"
runtime = "1.10.0"
uiTooling = "1.10.0"
uiToolingPreview = "1.10.0"




[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebaseCommonKtx" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "uiTooling" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
